import type { EncounterTable, TerrainId } from '../domain.js';

/**
 * Standard wandering-encounter tables, one per terrain, in the classic
 * DMG-style shape: low rolls are the dangerous outliers, the middle is
 * bread-and-butter monsters, and high rolls are color, hazards, or nothing.
 * Creatures are drawn from the SRD 5.1 bestiary and pitched at tier 1–2
 * parties; the DM edits after loading like any hand-built table.
 */
export type EncounterPreset = Omit<EncounterTable, 'id' | 'enabled'>;

function preset(
  name: string,
  terrains: TerrainId[],
  lines: [string, string?][],
): EncounterPreset {
  return {
    name,
    terrains,
    die: '1d12',
    entries: lines.map(([text, quantity], i) => ({
      min: i + 1,
      max: i + 1,
      text,
      quantity: quantity ?? '',
    })),
  };
}

export const ENCOUNTER_PRESETS: EncounterPreset[] = [
  preset('Plains encounters', ['plains'], [
    ['Ankheg bursting from beneath the turf'],
    ['Hobgoblin patrol marching in formation', '2d4'],
    ['Ogre dragging a laden sledge toward its lair'],
    ['Mounted bandits shadowing the party at a distance', '2d6'],
    ['Giant wasps buzzing low over the grass', '1d4'],
    ['Wolves circling a wounded elk', '1d6'],
    ['Giant boar rooting through a berry thicket'],
    ['Herd of wild horses grazing — skittish but harmless'],
    ['Merchant caravan with hired guards, glad to trade news'],
    ['Vultures circling something dead about a mile off'],
    ['Lone rider pushing a lathered horse, in a hurry'],
    ['Rolling grass and wind — no encounter'],
  ]),
  preset('Forest encounters', ['forest'], [
    ['Owlbear crashing through the underbrush'],
    ['Goblin ambush from the treetops', '2d6'],
    ['Giant spiders descending on silk lines', '1d4'],
    ['Bandit camp around a low, smoky fire', '2d4'],
    ['Hungry wolves pacing the party', '2d4'],
    ['Awakened trees standing silent sentinel', '1d2'],
    ['Black bears defending a carcass', '1d2'],
    ['Sprites demanding to know the party’s business', '1d4'],
    ['Game trail — deer bolt; good foraging nearby'],
    ['A hermit druid who knows every path in these woods'],
    ['Abandoned campsite: cold ashes and a dropped locket'],
    ['Birdsong and dappled light — no encounter'],
  ]),
  preset('Hills encounters', ['hills'], [
    ['Hill giant hurling boulders for sport'],
    ['Orc raiding party moving fast and low', '2d4'],
    ['Worgs loping downslope, tongues lolling', '1d4'],
    ['Gnoll hunting pack on a blood trail', '1d6'],
    ['Giant eagles riding the thermals overhead', '1d2'],
    ['Lions stalking the party from the tall grass', '1d2'],
    ['Giant goats butting over territory', '1d4'],
    ['Shepherd and flock; the dogs bark a warning'],
    ['Dwarf prospectors arguing over a claim', '1d4'],
    ['Rockslide scar cutting across the trail — slow going'],
    ['Ancient cairn with a loose capstone'],
    ['Wind over the heather — no encounter'],
  ]),
  preset('Mountains encounters', ['mountains'], [
    ['Wyvern diving from a high ledge'],
    ['Griffons defending a cliffside nest', '1d2'],
    ['Ogres camped athwart the pass', '1d2'],
    ['Orc war band on the march', '2d6'],
    ['Harpies singing above a chasm', '1d4'],
    ['Berserkers from a high clan-hold, spoiling for a fight', '1d4'],
    ['Giant goats on an impossible ledge', '1d6'],
    ['Giant eagle watching with uncanny intelligence'],
    ['Narrow ledge crumbling underfoot — dangerous crossing'],
    ['Pilgrims climbing to a shrine at the summit'],
    ['Picked-clean bones in an abandoned eyrie'],
    ['Thin cold air and silence — no encounter'],
  ]),
  preset('Desert encounters', ['desert'], [
    ['Giant scorpions erupting from beneath the sand', '1d3'],
    ['Gnoll war band trailing the party since dawn', '2d4'],
    ['Dust mephits spinning inside a dust devil', '1d6'],
    ['Desert raiders on camels, demanding tribute', '2d6'],
    ['Giant hyenas loping across the hardpan', '1d4'],
    ['Swarm of insects — locusts strip everything green'],
    ['Jackals keeping pace at the edge of sight', '2d6'],
    ['Giant lizard sunning itself on a rock'],
    ['Nomad caravan willing to share water and news'],
    ['Half-buried ruin, its doorway scoured by sand'],
    ['Mirage — a shimmering oasis that isn’t there'],
    ['Heat haze and empty dunes — no encounter'],
  ]),
  preset('Swamp encounters', ['swamp'], [
    ['Black dragon wyrmling patrolling its territory'],
    ['Lizardfolk hunters poling flatboats', '2d4'],
    ['Crocodiles floating like logs', '1d2'],
    ['Ghouls rising from a drowned barrow', '1d4'],
    ['Stirges rising in a whining cloud', '2d6'],
    ['Giant frogs plopping off their perches', '1d6'],
    ['Giant constrictor snake coiled in the shallows'],
    ['Swarm of insects — biting flies, relentless'],
    ['Will-o’-wisp lights bobbing over deep water'],
    ['Hermit’s stilt hut, its occupant watching in silence'],
    ['Sunken statue of a god no one remembers'],
    ['Mist and frog-song — no encounter'],
  ]),
  preset('Open water encounters', ['water'], [
    ['Merrow rising around the hull', '1d4'],
    ['Hunter shark bumping the keel, testing'],
    ['Sahuagin raiders swarming up the sides', '2d4'],
    ['Giant octopus grasping at the oars'],
    ['Pirate sloop changing course to intercept', '2d6'],
    ['Swarm of quippers churning the water red'],
    ['Merfolk curious about the vessel', '1d6'],
    ['Whale breaching nearby — awesome, harmless'],
    ['Floating wreckage: salvage, or a survivor'],
    ['Squall building fast on the horizon'],
    ['Dead calm, and the fog thickening'],
    ['Fair winds and open water — no encounter'],
  ]),
  preset('Coast encounters', ['coast'], [
    ['Harpies nesting on the sea cliffs', '1d4'],
    ['Sahuagin raiding party wading out of the surf', '2d6'],
    ['Giant crabs among the weed-slick rocks', '1d6'],
    ['Smugglers unloading crates, hostile to witnesses', '2d4'],
    ['Reef sharks prowling the shallows', '1d4'],
    ['Giant eagle fishing the breakers'],
    ['Merfolk offering to trade shells and salvage', '1d4'],
    ['Beached whale carcass, scavengers squabbling over it'],
    ['Fisherfolk mending nets, full of local rumor'],
    ['Shipwreck broken on the rocks, exposed at low tide'],
    ['Strange webbed tracks leading out of the surf'],
    ['Gulls and rolling waves — no encounter'],
  ]),
  preset('Tundra encounters', ['tundra'], [
    ['Frost giant hunting far from its hold'],
    ['Winter wolves conversing in low growls', '1d2'],
    ['Polar bear ambushing from a snowbank'],
    ['Berserkers in furs, hostile to trespassers', '1d4'],
    ['Ice mephits skittering across the crust', '1d6'],
    ['Saber-toothed tiger stalking the rearmost traveler'],
    ['Wolves made desperate by hunger', '2d4'],
    ['Mammoth herd — deadly if spooked', '1d4'],
    ['Fur-clad hunters willing to share a fire', '2d4'],
    ['Whiteout rolling in — visibility collapsing'],
    ['Frozen corpse, pack still strapped to its back'],
    ['Blue silence over the snow — no encounter'],
  ]),
  preset('Jungle encounters', ['jungle'], [
    ['Giant ape beating its chest in challenge'],
    ['Giant constrictor snake dropping from above'],
    ['Panthers hunting from the canopy shade', '1d2'],
    ['Poachers hostile to witnesses', '2d4'],
    ['Giant wasps boiling from a paper nest', '1d6'],
    ['Swarm of insects — stinging ants on the march'],
    ['Giant lizards sprawled across the trail', '1d4'],
    ['Apes hooting an alarm through the canopy', '2d4'],
    ['Vine-choked ruin half-swallowed by the jungle'],
    ['Brilliant birds — one repeats words it has heard'],
    ['Fresh machete-cut trail crossing the party’s path'],
    ['Dripping green stillness — no encounter'],
  ]),
  preset('Urban encounters', ['urban'], [
    ['Doppelganger wearing a familiar face'],
    ['Thugs demanding a “street toll”', '1d4'],
    ['Cultists in plain clothes, recruiting', '2d4'],
    ['A spy has been tailing the party for blocks'],
    ['Pickpocket working the crowd — Perception or lose a purse'],
    ['Swarm of rats boiling out of a sewer grate'],
    ['City watch with pointed questions', '1d4'],
    ['Street festival choking the avenue with revelers'],
    ['Merchant hawking maps “guaranteed genuine”'],
    ['Beggar selling a genuinely useful rumor'],
    ['Funeral procession — all traffic stops for it'],
    ['Quiet streets — no encounter'],
  ]),
  preset('Badlands encounters', ['badlands'], [
    ['Basilisk among suspiciously lifelike “statues”'],
    ['Ogres cracking bones at a guttering fire', '1d2'],
    ['Gnolls on the scent', '2d4'],
    ['Orc scouts marking territory with crude signs', '1d6'],
    ['Giant vultures circling lower', '1d3'],
    ['Cockatrice strutting out of a crevice'],
    ['Hyenas laughing in the gullies', '2d4'],
    ['Giant lizard motionless on a shelf of rock'],
    ['Choking dust storm rising — seek shelter'],
    ['Prospector’s camp, abandoned in a hurry'],
    ['Colossal weathered bones jutting from a ridge'],
    ['Cracked earth and shimmering heat — no encounter'],
  ]),
  // The terrain-agnostic fallback: rolls on unpainted hexes, or wherever no
  // terrain table matches, land here instead of "improvise!".
  preset('Wilderness (any terrain)', [], [
    ['Ogre looking for an easy meal'],
    ['Bandits sizing up the party', '2d6'],
    ['Goblin scouts who bolt toward their warren', '2d4'],
    ['Wolves keeping pace at the treeline', '1d6'],
    ['Worgs hunting without riders', '1d2'],
    ['Stirges dropping from above', '1d6'],
    ['Skeletons of an old battle, still standing watch', '1d6'],
    ['Traveling peddler with an overloaded mule'],
    ['Pilgrims or refugees, footsore and wary'],
    ['Abandoned campsite — cold fire, scattered gear'],
    ['The weather turns fast — seek shelter or push through'],
    ['An uneventful stretch — no encounter'],
  ]),
];
